apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: lab-gateway
spec:
  secretName: argocd-tls
  dnsNames:
    - argocd.tekton-lab.test
  issuerRef:
    name: step-ca-acme
    kind: ClusterIssuer
