apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 10.4.0
      helm:
        valueFiles:
          - $values/helm/argocd/values.yaml
    - repoURL: git@github.com:tilraunastofan/kind-lab-argo-kargo-tekton.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:tilraunastofan/kind-lab-argo-kargo-tekton.git
      targetRevision: main
      path: helm/argocd/extras
      directory:
        include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
