apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tilraunastofan/kind-lab-argo-kargo-tekton.git
    targetRevision: main
    path: helm/gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: lab-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
