apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smoke-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:tilraunastofan/kind-lab-argo-kargo-tekton.git
    targetRevision: main
    path: helm/smoke-test
  destination:
    server: https://kubernetes.default.svc
    namespace: smoke-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 2m
