#!/usr/bin/env bash

log()  { printf '\033[1;36m==>\033[0m %s\n' "$*" >&2; }
warn() { printf '\033[1;33m!!\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

require_cmd() {
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || die "required command not found: ${cmd}"
  done
}

# wait_for <description> <timeout_seconds> <check_fn> [args...]
wait_for() {
  local desc="$1" timeout="$2"
  shift 2
  local elapsed=0
  until "$@" >/dev/null 2>&1; do
    if [ "${elapsed}" -ge "${timeout}" ]; then
      die "timed out after ${timeout}s waiting for: ${desc}"
    fi
    sleep 3
    elapsed=$((elapsed + 3))
  done
  log "${desc}: ready"
}

# ensure_token <VAR_NAME>
#
# Makes sure VAR_NAME is set AND exported in the calling shell, generating and
# persisting a random value if it doesn't exist anywhere yet. Lookup order:
#   1. the environment (already exported by ~/.zshrc sourcing ~/.tokens),
#   2. the last `export VAR_NAME=...` line in $TOKENS_FILE (~/.tokens) — needed
#      because a value generated by an EARLIER script in this same bootstrap
#      run was appended to the file, but the parent shell that started
#      bootstrap.sh never re-sourced it,
#   3. otherwise generate `openssl rand -hex 24` and append it to the file.
# Call it directly, not inside $(...): it must export into the caller's shell.
TOKENS_FILE="${TOKENS_FILE:-${HOME}/.tokens}"
ensure_token() {
  local name="$1" value
  value="${!name:-}"

  if [ -z "${value}" ] && [ -f "${TOKENS_FILE}" ]; then
    # ^export anchors the match so a commented-out `#export X=` is ignored;
    # the second sed strips one pair of surrounding quotes if present.
    value="$(sed -n "s/^export ${name}=\(.*\)\$/\1/p" "${TOKENS_FILE}" | tail -1 | sed -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'\$/\1/")"
  fi

  if [ -z "${value}" ]; then
    value="$(openssl rand -hex 24)"

    # Ensure file is created with safe permissions if it doesn't exist yet
    if [ ! -f "${TOKENS_FILE}" ]; then
      (umask 077 && : > "${TOKENS_FILE}")
    elif [ -f "${TOKENS_FILE}" ]; then
      # File exists; check if it has unsafe permissions (group/other readable)
      local file_mode
      file_mode="$(stat -c '%a' "${TOKENS_FILE}" 2>/dev/null)" || file_mode=""
      if [ -n "${file_mode}" ] && ! [[ "${file_mode}" =~ ^6[0]0$ ]]; then
        # File is group/other-readable; warn but don't chmod
        warn "TOKENS_FILE ${TOKENS_FILE} is readable by other users; please run: chmod 600 ${TOKENS_FILE}"
      fi
    fi

    printf '\n# generated by scripts/lib.sh ensure_token\nexport %s=%s\n' "${name}" "${value}" >> "${TOKENS_FILE}"
    log "generated ${name} and appended it to ${TOKENS_FILE}"
  fi

  export "${name}=${value}"
}

CLUSTER_NAME="tekton-lab"
LAB_DOMAIN="tekton-lab.test"
STEPCA_PORT="9443"
