#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/lib.sh
source "${SCRIPT_DIR}/lib.sh"

# Creates/refreshes the vector-clickhouse Secret in the logging namespace,
# which helm/vector/values.yaml maps into Vector's env as
# CLICKHOUSE_LOGS_VECTOR_PASSWORD. Same out-of-band, idempotent pattern as
# datadog-secret-up.sh: the value comes from ~/.tokens (auto-generated by
# ensure_token, shared with clickhouse-logs-up.sh which creates the matching
# ClickHouse user) and must never end up in Git.

main() {
  require_cmd kubectl openssl

  ensure_token CLICKHOUSE_LOGS_VECTOR_PASSWORD

  log "ensuring logging namespace exists"
  kubectl create namespace logging --dry-run=client -o yaml | kubectl apply -f -

  log "creating/refreshing vector-clickhouse in logging"
  kubectl -n logging create secret generic vector-clickhouse \
    --from-literal=password="${CLICKHOUSE_LOGS_VECTOR_PASSWORD}" \
    --dry-run=client -o yaml | kubectl apply -f -

  log "vector-clickhouse ready in logging"
}

main "$@"
